In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/movie-review-sentiment-analysis-kernels-only/test.tsv
/kaggle/input/movie-review-sentiment-analysis-kernels-only/sampleSubmission.csv
/kaggle/input/movie-review-sentiment-analysis-kernels-only/train.tsv


In [2]:
train = pd.read_csv('../input/movie-review-sentiment-analysis-kernels-only/train.tsv', sep="\t")
test = pd.read_csv('../input/movie-review-sentiment-analysis-kernels-only/test.tsv', sep="\t")
sub = pd.read_csv('../input/movie-review-sentiment-analysis-kernels-only/sampleSubmission.csv', sep=",")

In [3]:
train.head()

PhraseId  SentenceId                                             Phrase  \
0         1           1  A series of escapades demonstrating the adage ...   
1         2           1  A series of escapades demonstrating the adage ...   
2         3           1                                           A series   
3         4           1                                                  A   
4         5           1                                             series   

   Sentiment  
0          1  
1          2  
2          2  
3          2  
4          2

**Counting the number of Reviews**

In [4]:
len(train)

156060

**Displaying a review**

In [5]:
train['Phrase'][0]

'A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .'

**Checking for missing values**

In [6]:
train.isnull().sum()

PhraseId      0
SentenceId    0
Phrase        0
Sentiment     0
dtype: int64

There are no missing values in the data.In case of text data there can be empty strings in place of null values.

**Checking for Empty Strings**

In [7]:
mystring='Hello'
empty=' '

In [8]:
mystring.isspace()

False

In [9]:
empty.isspace()

True

In [10]:
blanks=[]
for i,p,s,rb,s in train.itertuples():
    if rb.isspace():
        blanks.append(i)
        

In [11]:
blanks

[2005]

so index position 2005 has a blank string 

In [12]:
train.drop(blanks,inplace=True)

In [13]:
len(train)

156059

We can see that the blank or the empty movie review has been removed from the dataset.

**Splitting the data into test train set **

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X=train['Phrase']
#X

In [16]:
y=train['Sentiment']
#y

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

**Model creation **

In [18]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

In [19]:
text_clf=Pipeline([('tfidf',TfidfVectorizer()),('clf',LinearSVC())])

In [20]:
text_clf.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
               

In [21]:
predictions=text_clf.predict(X_test)

**Creating a confusion matrix,Classificationreport and accuracy score**

In [22]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [23]:
print(confusion_matrix(y_test,predictions))

[[  636  1062   356    52     4]
 [  499  3711  3694   378     9]
 [   99  1842 19677  1978    85]
 [   12   302  3978  4936   638]
 [    0    28   311  1611   920]]


In [24]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.51      0.30      0.38      2110
           1       0.53      0.45      0.49      8291
           2       0.70      0.83      0.76     23681
           3       0.55      0.50      0.52      9866
           4       0.56      0.32      0.41      2870

    accuracy                           0.64     46818
   macro avg       0.57      0.48      0.51     46818
weighted avg       0.62      0.64      0.62     46818



In [25]:
print(accuracy_score(y_test,predictions))

0.6382160707420222
