In this kernel I will be covering the basics of Numpy.This is a kernel in process and i will keep on updating this in the coming days.If you like my work please do vote.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

**Creating Arrays**

In [2]:
my_list1=[1,2,3,4]
my_list1

[1, 2, 3, 4]

In [3]:
# Making an array using a list
my_array1=np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [4]:
my_list2=[11,22,33,44]

In [5]:
#Combining the two lists 
my_lists=[my_list1,my_list2]

In [6]:
#Creating a 2D array
my_array2=np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [7]:
my_array2.shape

(2, 4)

In [8]:
#Finding out the datatype of the array 
my_array2.dtype

dtype('int64')

In [9]:
#Creating an array of all zeros
my_zeros_array=np.zeros(5)
my_zeros_array                   

array([0., 0., 0., 0., 0.])

In [10]:
#Checking the datatype of Zero Array 
my_zeros_array.dtype

dtype('float64')

In [11]:
#Creating an array of ones 
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#Creating empty arrays 
np.empty(5)

array([0., 0., 0., 0., 0.])

In [13]:
#Creating an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
#Creating an array starting with 5 and enfing with 50 with a space of 2
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

**Using arrays and scalars **

In [16]:
arr1=np.array([[1,2,3,4],[8,9,10,11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [17]:
#Multiplying two arrays 
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [18]:
#Subtraction on arrays
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
#Scalar multiplication 
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [20]:
#Exponenetial operation
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

**Indexing Arrays**